#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.4f1_4f139db2fdbd"
#define UNITY_VERSION_FULL_NICE "2019.3.4f1 (4f139db2fdbd)"
#define UNITY_VERSION_BLD 5182365
#define UNITY_VERSION_DATE 1583315198
#define UNITY_VERSION_WIN "2019.3.4.5182365"
#define UNITY_VERSION_BRANCH "2019.3/release"
